node('built-in') 
{
    stage('Continuous Download-master') 
	{
    git 'https://github.com/SitaMaturi/multibranch.git'
	}
    stage('Continuous Build-master') 
	{
    sh label: '', script: 'mvn package'
	}
}
